/**
     * VotingV2 ABI (Human-Readable Format)
     * Auto-generated by scripts/generate-abi.js
     */
    export const VOTINGV2_ABI = [
  "error AddressEmptyCode",
  "error ERC1967InvalidImplementation",
  "error ERC1967NonPayable",
  "error FailedCall",
  "error InvalidInitialization",
  "error NotInitializing",
  "error OwnableInvalidOwner",
  "error OwnableUnauthorizedAccount",
  "error UUPSUnauthorizedCallContext",
  "error UUPSUnsupportedProxiableUUID",
  "event Initialized(uint64 version)",
  "event OwnershipTransferred(address previousOwner indexed, address newOwner indexed)",
  "event ProposalCreated(uint256 id indexed, string description, uint256 deadline)",
  "event ProposalExecuted(uint256 id indexed)",
  "event Upgraded(address implementation indexed)",
  "event Voted(uint256 proposalId indexed, address voter indexed, uint256 voteCount)",
  "function UPGRADE_INTERFACE_VERSION() view returns (string )",
  "function addVoter(address _voter) nonpayable",
  "function createProposal(string _description) nonpayable",
  "function executeProposal(uint256 _proposalId) nonpayable",
  "function getAllProposals() view returns (tuple[] )",
  "function hasVoted(address , uint256 ) view returns (bool )",
  "function initialize() nonpayable",
  "function owner() view returns (address )",
  "function proposalCount() view returns (uint256 )",
  "function proposals(uint256 ) view returns (string description, uint256 voteCount, uint256 deadline, bool executed)",
  "function proxiableUUID() view returns (bytes32 )",
  "function renounceOwnership() nonpayable",
  "function transferOwnership(address newOwner) nonpayable",
  "function upgradeToAndCall(address newImplementation, bytes data) payable",
  "function vote(uint256 _proposalId) nonpayable",
  "function voters(address ) view returns (bool )",
  "function votingDuration() view returns (uint256 )"
];